name: Build and test

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]


jobs:
  build:
    runs-on: ubuntu-latest
    stepts:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
